showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - status
    - icon
    - traffic
  - - text
hideTrayIcon: false
editor: 0
theme: 1
showNotifications: true
proxyOrder: 1
connShowProcess: true
showTrayProxyDelayIndicator: true
randomMixedPort: false
latencyUrl: https://www.google.com
latencyTimeout: 5000
connProxy: 0
connChainType: 0
showProxyFilter: true
hideUnselectableGroup: true
useSystemEmoji: true
shortcutShowHideDashboard: ""
visibleOnAllWorkspaces: true
systemTheme: true
trayProxiesStyle: 0
