showNewVersionIcon: true
hideAfterStartup: false
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
editor: 0
theme: 1
showNotifications: true
proxyOrder: 1
connShowProcess: true
showTrayProxyDelayIndicator: true
randomMixedPort: true
latencyUrl: https://www.google.com
latencyTimeout: 3000
connProxy: 0
connChainType: 0
